# ===========================
# MAIN PARAMETERS
# ===========================
# These are the main parameters you'll want to customize
research_interests:   "${projectDir}/config/research_interests.md"
journals_tsv:         "${projectDir}/config/journals.tsv"

zotero_user_id:       "1508765"
zotero_collection_id: "U3T98NSQ"
zotero_library_type:  "user"

# ===========================
# OTHER PARAMETERS
# ===========================
# ===========================
# Backend Configuration
# ===========================
# from:               "journals_tsv"
# from_json_input:    "articles.json"
# from_duckdb_input:  "papers_please.duckdb"
# to:                 "articles_json"
# to_json_outdir:     "./results"

# days_back: 8

# ===========================
# LLM Models Configuration
# ===========================
# batch_size:                         10
# metadata_extraction_model:          "gemini-2.5-flash-lite"
# metadata_extraction_system_prompt:  "${projectDir}/prompts/metadata_extraction.md"
# screening_model:                    "gemini-2.5-flash-lite"
# screening_system_prompt:            "${projectDir}/prompts/screening.md"
# prioritization_model:               "gemini-2.5-flash-lite"
# prioritization_system_prompt:       "${projectDir}/prompts/prioritization.md"

# ===========================
# Others
# ===========================
# debug: false
