name: Weekly Literature Screening

on:
  # Run every Monday at 9 AM UTC
  schedule:
    - cron: '0 9 * * 1'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  screen-papers:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hour timeout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Nextflow
      uses: nf-core/setup-nextflow@v2
      with:
        version: latest-stable

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Nextflow secrets
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        SPRINGER_META_API_KEY: ${{ secrets.SPRINGER_META_API_KEY }}
        ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
      run: |
        # Set Nextflow secrets from GitHub secrets
        nextflow secrets set GOOGLE_API_KEY "$GOOGLE_API_KEY"
        nextflow secrets set USER_EMAIL "$USER_EMAIL"
        nextflow secrets set ZOTERO_API_KEY "$ZOTERO_API_KEY"

        # Optional secret - only set if available
        if [ -n "$SPRINGER_META_API_KEY" ]; then
          nextflow secrets set SPRINGER_META_API_KEY "$SPRINGER_META_API_KEY"
        fi

        echo "✓ Nextflow secrets configured"

    # - name: Debug with tmate
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true

    - name: Run Nextflow pipeline
      env:
        NXF_ANSI_LOG: false
      run: |
        DEBUG_FLAG=""
        if [ "${{ github.ref_name }}" != "main" ]; then
          DEBUG_FLAG="--debug"
        fi

        nextflow run main.nf \
          -params-file config/pipeline_parameters.yaml \
          --backend_from tsv \
          --backend_to zotero \
          -ansi-log false \
          $DEBUG_FLAG

    - name: Generate pipeline summary
      if: always()
      run: |
        echo "## Pipeline Execution Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if [ -f .nextflow.log ]; then
          echo "### Pipeline Status" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          tail -n 20 .nextflow.log >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload pipeline logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nextflow-logs-${{ github.run_number }}
        path: |
          .nextflow.log
          .nextflow/**
        retention-days: 14
        compression-level: 9

    - name: Upload work directory logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: work-logs-${{ github.run_number }}
        path: |
          work/**/.command.log
          work/**/.command.err
        retention-days: 7
        compression-level: 9

    - name: Notify on failure
      if: failure()
      run: |
        echo "::error::Pipeline execution failed. Check the artifacts for detailed logs."
        echo "## ⚠️ Pipeline Failed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Please check the uploaded artifacts for detailed error logs:" >> $GITHUB_STEP_SUMMARY
        echo "- nextflow-logs-${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "- work-logs-${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
